'use strict';

/**
 * @ngdoc function
 * @name loWbApp.controller:SitemapCtrl
 * @description
 * # SitemapCtrl
 * Controller of the loWbApp
 */
angular.module('loWbApp')
  .controller('SitemapCtrl', function ($rootScope,landingLoader) {
    landingLoader.firstLoad();
        $rootScope.showHeader = true;
        $(window).scrollTop(0);
        var vm = this;
        vm.courseName = [
        	{name:'B.Arch'},
        	{name:'M.Arch'},
        	{name:'M.Phit/Ph.D'},
        	{name:'M.Planning'},
        	{name:'B.Com'},
        	{name:'M.Com'},
        	{name:'B.Des'},
        	{name:'B.Arch'},
        	{name:'M.Arch'},
        	{name:'M.Phit/Ph.D'},
        	{name:'B.Des'},
        	{name:'B.Arch'},
        	{name:'M.Arch'},
        	{name:'M.Phit/Ph.D'},
        	{name:'M.Planning'},
        	{name:'B.Com'},
        	{name:'M.Com'},
        	{name:'B.Des'},
        	{name:'B.Arch'},
        	{name:'M.Arch'},
        	{name:'M.Phit/Ph.D'},
        	{name:'M.Planning'},
        	{name:'B.Com'},
        	{name:'M.Com'},
        	{name:'B.Des'},
        	{name:'B.Arch'},
        	{name:'M.Arch'},
        	{name:'M.Phit/Ph.D'},
        	{name:'B.Des'},
        	{name:'B.Arch'},
        	{name:'M.Arch'},
        	{name:'M.Phit/Ph.D'},
        	{name:'M.Planning'},
        	{name:'B.Com'},
        	{name:'M.Com'},
        	{name:'B.Des'},
        	{name:'B.Arch'},
        	{name:'M.Arch'},
        	{name:'M.Phit/Ph.D'},
        	{name:'M.Planning'},
        	{name:'B.Com'},
        	{name:'M.Com'},
        	{name:'B.Des'},
        	{name:'B.Arch'},
        	{name:'M.Arch'},
        	{name:'M.Phit/Ph.D'},
        	{name:'M.Planning'},
        	{name:'B.Com'},
        	{name:'M.Com'},
        	{name:'B.Des'},
        	{name:'B.Arch'},
        	{name:'M.Arch'},
        	{name:'M.Phit/Ph.D'},
        	{name:'B.Des'},
        	{name:'B.Arch'},
        	{name:'M.Arch'},
        	{name:'M.Phit/Ph.D'},
        	{name:'M.Planning'},
        	{name:'B.Com'},
        	{name:'M.Com'},
        	{name:'B.Des'},
        	{name:'B.Arch'},
        	{name:'M.Arch'},
        	{name:'M.Phit/Ph.D'},
        	{name:'B.Des'},
        	{name:'B.Arch'},
        	{name:'M.Arch'},
        	{name:'M.Phit/Ph.D'},
        	{name:'M.Planning'},
        	{name:'B.Com'},
        	{name:'M.Com'},
        	{name:'B.Des'},
        	{name:'B.Arch'},
        	{name:'M.Arch'},
        	{name:'M.Phit/Ph.D'},
        	{name:'M.Planning'},
        	{name:'B.Com'},
        	{name:'M.Com'},
        	{name:'B.Des'},
        	{name:'B.Des'},
        	{name:'B.Arch'},
        	{name:'M.Arch'},
        	{name:'M.Phit/Ph.D'},
        	{name:'B.Arch'},
        	{name:'M.Arch'},
        	{name:'M.Phit/Ph.D'},
        	{name:'M.Planning'},
        	{name:'B.Com '},
        	{name:'M.Com'},
        	{name:'B.Des'},
        	{name:'B.Arch'},
        	{name:'M.Arch'},
        	{name:'M.Phit/Ph.D'},
        	{name:'M.Planning'},
        	{name:'B.Com'},
        	{name:'M.Com'},
        	{name:'B.Des'},
        ];
        vm.examName = [
        	{name:'NATA'},
        	{name:'GAT'},
        	{name:'JEE'},
        	{name:'NIFT'},
        	{name:'NEED'},
        	{name:'CEED'},
        	{name:'UPES'},
        	{name:'GPAT'},
        	{name:'ICAR AIEFAUG'},
        	{name:'AILET'},
        	{name:'NATA'},
        	{name:'GAT'},
        	{name:'JEE'},
        	{name:'NIFT'},
        	{name:'NEED'},
        	{name:'CEED'},
        	{name:'UPES'},
        	{name:'GPAT'},
        	{name:'ICAR AIEFAUG'},
        	{name:'AILET'},
        	{name:'NATA'},
        	{name:'GAT'},
        	{name:'JEE'},
        	{name:'NIFT'},
        	{name:'NEED'},
        	{name:'CEED'},
        	{name:'UPES'},
        	{name:'GPAT'},
        	{name:'ICAR AIEFAUG'},
        	{name:'AILET'},
        	{name:'NATA'},
        	{name:'GAT'},
        	{name:'JEE'},
        	{name:'NIFT'},
        	{name:'NEED'},
        	{name:'CEED'},
        	{name:'UPES'},
        	{name:'GPAT'},
        	{name:'ICAR AIEFAUG'},
        	{name:'AILET'},
        	{name:'NATA'},
        	{name:'GAT'},
        	{name:'JEE'},
        	{name:'NIFT'},
        	{name:'NEED'},
        	{name:'CEED'},
        	{name:'UPES'},
        	{name:'GPAT'},
        	{name:'ICAR AIEFAUG'},
        	{name:'AILET'},
        	{name:'NATA'},
        	{name:'GAT'},
        	{name:'JEE'},
        	{name:'NIFT'},
        	{name:'NEED'},
        	{name:'CEED'},
        	{name:'UPES'},
        	{name:'GPAT'},
        	{name:'ICAR AIEFAUG'},
        	{name:'AILET'},
        	{name:'NATA'},
        	{name:'GAT'},
        	{name:'JEE'},
        	{name:'NIFT'},
        	{name:'NEED'},
        	{name:'CEED'},
        	{name:'UPES'},
        	{name:'GPAT'},
        	{name:'ICAR AIEFAUG'},
        	{name:'AILET'},
        ];
  });
